# controllers.yaml
controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

# Add MoveIt controllers
# moveit_controller_manager:
#   ros__parameters:
#     use_controller_manager: true
#     controller_names:
#       - joint_trajectory_controller
#     controller_list:
#       - name: joint_trajectory_controller
#         action_ns: follow_joint_trajectory
#         type: FollowJointTrajectory
#         default: true
#         joints:
#           - shoulder_pan_joint
#           - shoulder_lift_joint
#           - elbow_joint
#           - wrist_1_joint
#           - wrist_2_joint
#           - wrist_3_joint